### ISSUE TITLE
Just before/after move checklist

### ISSUE THREAD

**Issue by versatilehuman** [versatilehuman/fpdccweb#70]
- [x] Update domain settings on Dreampress (https://help.dreamhost.com/hc/en-us/articles/216385467-Nameservers-overview & https://help.dreamhost.com/hc/en-us/articles/115004353927-Changing-the-name-of-a-DreamPress-domain)
- [x] Point domain from firewall
- [x] Turn off "Discourage search engines from indexing this site"
- [x] Add Google Analytics
- [x] Login to Jetpack to reconnect (under step 1: https://help.dreamhost.com/hc/en-us/articles/115004353927-Changing-the-name-of-a-DreamPress-domain)
- [x] Test contact forms after move
- [x] Map integrations: https://github.com/fpdcc/trailsy/milestone/15
- [x] Map data updates: https://github.com/fpdcc/webmap_data_updates/issues/170
- [x] Update .htaccess file with full URL 
- [x] Update PDF map URLs to https://
- [x] Redirect to https and naked domain https://wordpress.org/plugins/really-simple-ssl/
- [x] Update database URLs https://help.dreamhost.com/hc/en-us/articles/360003304711-Changing-all-URLs-in-your-WordPress-database
- [x] Double check forwarding in htaccess (look for //)
